services:
  # train

  app:
    build:
      context: .
      target: base

    working_dir: /app

    ports:
      - "${GRADIO_SERVER_PORT}:7860"

    environment:
      API_URL: http://api:8000
      GRADIO_SERVER_NAME: "${GRADIO_SERVER_NAME}"
      GRADIO_SERVER_PORT: "${GRADIO_SERVER_PORT}"

    command:
      - uv
      - run
      - --package
      - app
      - python
      - -m
      - app.app


  api:
    build:
      context: .
      target: base

    working_dir: /app

    ports:
      - "8000:8000"

    environment:
      MLFLOW_URL: http://mlflow:5000

    volumes:
      - ./mlruns:/app/mlruns

    command:
      - uv
      - run
      - --package
      - api
      - uvicorn
      - api.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"


  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.14.0-full

    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////app/mlruns/mlflow.db

    ports:
      - "5000:5000"

    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "${MLFLOW_SERVER_ALLOWED_HOSTS}"
      MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: "${MLFLOW_SERVER_CORS_ALLOWED_ORIGINS}"

    volumes:
      - ./mlruns:/app/mlruns


  # app:
  #   profiles: ["main"]
  #   build:
  #     context: .
  #     target: base
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: uv run python src/text_classifier/main.py

  # ml-pipeline:
  #   profiles: ["ml-pipeline"]
  #   build:
  #     context: .
  #     target: base
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: uv run dvc repro

  # notebook:
  #   profiles: ["notebook"]
  #   build:
  #     context: .
  #     target: notebook
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: uv run jupyter lab --ip=0.0.0.0 --allow-root --no-browser

  dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    command: sleep infinity
