services:
  app:
    build:
      context: .
      target: base

    working_dir: /app

    ports:
      - "${GRADIO_SERVER_PORT}:7860"

    environment:
      API_URL: http://api:8000
      GRADIO_SERVER_NAME: "${GRADIO_SERVER_NAME}"
      GRADIO_SERVER_PORT: "${GRADIO_SERVER_PORT}"

    depends_on:
      - api

    command:
      - uv
      - run
      - --package
      - app
      - python
      - -m
      - app.app


  api:
    build:
      context: .
      target: base

    working_dir: /app

    ports:
      - "8000:8000"

    environment:
      MLFLOW_URL: http://mlflow:5000

    volumes:
      - ./mlruns:/app/mlruns

    depends_on:
      - mlflow

    command:
      - uv
      - run
      - --package
      - api
      - uvicorn
      - api.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"


  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.14.0-full

    working_dir: /mlruns

    depends_on:
      - seaweedfs

    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////data/mlflow.db
      - --artifacts-destination
      - s3://mlflow-artifacts

    ports:
      - "5000:5000"

    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "${MLFLOW_SERVER_ALLOWED_HOSTS}"
      MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: "${MLFLOW_SERVER_CORS_ALLOWED_ORIGINS}"
      MLFLOW_S3_ENDPOINT_URL: http://seaweedfs:8333
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}

    volumes:
      - mlflow-data:/data


  seaweedfs:
    image: chrislusf/seaweedfs:4.45

    command: server -dir=/data -s3

    ports:
      - "8333:8333"

    environment:
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}

    volumes:
      - seaweedfs-data:/data


  train-pipe:
    profiles: ["train-pipe"]

    working_dir: /app

    build:
      context: .
      target: train

    environment:
      MLFLOW_URL: http://mlflow:5000

    volumes:
      - ./.dvc:/app/.dvc
      - ./.git:/app/.git
      - ./artifacts:/app/artifacts
      - ./data:/app/data
      - ./dvc.lock:/app/dvc.lock
      - ./params.yaml:/app/params.yaml

    depends_on:
      - mlflow

    entrypoint:
      - uv
      - run
      - dvc
      - repro


  dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    command: sleep infinity


volumes:
  seaweedfs-data:
  mlflow-data:
