services:
  app:
    profiles: ["main"]
    build:
      context: .
      target: base
    working_dir: /app
    volumes:
      - .:/app
    command: uv run python src/text_classifier/main.py

  ml-pipeline:
    profiles: ["ml-pipeline"]
    build:
      context: .
      target: base
    working_dir: /app
    volumes:
      - .:/app
    command: uv run dvc repro

  notebook:
    profiles: ["notebook"]
    build:
      context: .
      target: notebook
    working_dir: /app
    volumes:
      - .:/app
    command: uv run jupyter lab --ip=0.0.0.0 --allow-root --no-browser

  dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    command: sleep infinity
