stages:
  preprocess:
    cmd: uv run src/text_classifier/scripts/preprocess.py

    deps:
      - data/datasets/raw_dataset.csv
      - src/text_classifier/config/config.py
      - src/text_classifier/config/logging_config.py
      - src/text_classifier/data/dataset.py
      - src/text_classifier/data/preprocessing.py

    outs:
      - data/datasets/preprocessed_dataset.parquet

  features:
    cmd: uv run src/text_classifier/scripts/build_features.py

    deps:
      - data/datasets/preprocessed_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/config/logging_config.py
      - src/text_classifier/data/dataset.py
      - src/text_classifier/data/embeddings.py
      - src/text_classifier/data/features.py

    outs:
      - data/datasets/feature_dataset.parquet

  build_model_dataset:
    cmd: uv run src/text_classifier/scripts/build_model_dataset.py

    deps:
      - data/datasets/feature_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/config/logging_config.py
      - src/text_classifier/data/dataset.py
      - src/text_classifier/data/model_data.py

    outs:
      - data/datasets/model_dataset.parquet

  train:
    cmd: uv run src/text_classifier/scripts/train.py

    deps:
      - data/datasets/model_dataset.parquet
      - params.yaml
      - src/text_classifier/config/config.py
      - src/text_classifier/config/logging_config.py
      - src/text_classifier/data/dataset.py
      - src/text_classifier/data/train_data.py
      - src/text_classifier/evaluation/metrics.py
      - src/text_classifier/evaluation/plots.py
      - src/text_classifier/model/models.py
      - src/text_classifier/model/pipeline.py
      - src/text_classifier/model/predictions.py
      - src/text_classifier/model/training.py
      - src/text_classifier/protocols.py
      - src/text_classifier/schema.py

    outs:
      - artifacts/train_metadata.json
