stages:
  preprocess:
    cmd: uv run src/text_classifier/scripts/preprocess.py

    deps:
      - data/datasets/raw_dataset.csv
      - src/text_classifier/config/config.py
      - src/text_classifier/data/preprocessing.py
      - src/text_classifier/save_load.py

    outs:
      - data/datasets/preprocessed_dataset.parquet

  features:
    cmd: uv run src/text_classifier/scripts/build_features.py

    deps:
      - data/datasets/preprocessed_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/data/features.py
      - src/text_classifier/save_load.py

    outs:
      - data/datasets/feature_dataset.parquet

  embeddings:
    cmd: uv run src/text_classifier/scripts/build_embeddings.py

    deps:
      - data/datasets/feature_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/data/embeddings.py
      - src/text_classifier/save_load.py

    outs:
      - data/datasets/embedding_dataset.parquet

  build_model_dataset:
    cmd: uv run src/text_classifier/scripts/build_model_dataset.py

    deps:
      - data/datasets/embedding_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/data/model_data.py
      - src/text_classifier/save_load.py

    outs:
      - data/datasets/model_dataset.parquet

  build_train_test_datasets:
    cmd: uv run src/text_classifier/scripts/build_train_test_datasets.py

    deps:
      - data/datasets/model_dataset.parquet
      - src/text_classifier/config/config.py
      - src/text_classifier/data/split.py
      - src/text_classifier/save_load.py
      - src/text_classifier/schema.py

    outs:
      - artifacts/label_encoder.joblib
      - data/datasets/splits/X_test.parquet
      - data/datasets/splits/X_train.parquet
      - data/datasets/splits/y_test.parquet
      - data/datasets/splits/y_train.parquet

  train:
    cmd: uv run src/text_classifier/scripts/train.py

    deps:
      - data/datasets/splits/X_train.parquet
      - data/datasets/splits/y_train.parquet
      - params.yaml
      - src/text_classifier/config/config.py
      - src/text_classifier/config/loader.py
      - src/text_classifier/data/loader.py
      - src/text_classifier/model/model_selection.py
      - src/text_classifier/model/models.py
      - src/text_classifier/model/pipeline.py
      - src/text_classifier/model/training.py
      - src/text_classifier/save_load.py
      - src/text_classifier/schema.py

    outs:
      - artifacts/train/best_estimator.joblib
      - artifacts/train/best_params.json
      - artifacts/train/best_score.txt
      - artifacts/train/cv_results.parquet
      - artifacts/train/run_id.txt

  evaluate:
    cmd: uv run src/text_classifier/scripts/evaluate.py

    deps:
      - data/datasets/splits/X_test.parquet
      - data/datasets/splits/y_test.parquet
      - artifacts/train/best_estimator.joblib
      - src/text_classifier/config/config.py
      - src/text_classifier/data/loader.py
      - src/text_classifier/model/predictions.py
      - src/text_classifier/save_load.py
      - src/text_classifier/schema.py
      - src/text_classifier/protocols.py
      - src/text_classifier/evaluation/eval.py
      - src/text_classifier/evaluation/metrics.py
      - src/text_classifier/evaluation/plots.py

    metrics:
      - artifacts/eval/metrics/test_metrics.json

    plots:
      - artifacts/eval/plots

    outs:
      - artifacts/eval/figs

  promote:
    cmd: uv run src/text_classifier/scripts/promote.py

    deps:
      - artifacts/eval/metrics/test_metrics.json
      - artifacts/train/model_version.txt
      - config/promote.yaml
      - src/text_classifier/config/config.py
      - src/text_classifier/promotion/promotion.py
      - src/text_classifier/save_load.py
      - src/text_classifier/scripts/promote.py
